site_name: Руководство по поиску в Google
site_description: Расширенное руководство для всех по технологии поиска в Google
site_author: morington
site_url: https://morington.github.io/google-search-guide

repo_name: morington/google-search-guide
repo_url: https://github.com/morington/google-search-guide

copyright: |
  Copyright &copy; 2024 <a href="https://github.com/morington" target="_blank" rel="noopener">Adam Morington</a>

theme:
  favicon: assets/images/guide.png
  logo: assets/images/icons8-google-100.png
  name: material
  features:
    # Toc
    - toc.integrate
    # Navigation
    - navigation.top
    - navigation.footer
    # Search
    - search.suggest
    - search.highlight
    # Content
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Переключить на тёмную тему
      primary: light blue
      accent: blue
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Переключить на светлую тему
      primary: blue
      accent: blue
  font:
    text: Nunito
    code: Roboto Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra:
  homepage: https://github.com/morington/google-search-guide
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/morington
      name: "Adam Morington"
    - icon: fontawesome/brands/github
      link: https://github.com/morington
      name: "GitHub - morington"

plugins:
  - social

nav:
  - 'Введение': index.md
  - 'Основы поиска в Google': google_search_basics.md
  - 'Операторы поиска': search_operators.md
  - 'Расширенная фильтрация': filters.md
  - 'Пользовательские настройки аккаунта': user_account_settings.md
  - 'Расширенный поиск': advanced_search.md
  - 'Безопасность в поиске': security_in_search.md
  - 'Google Dorks': google_dorks.md
  # DEBUG
  # - 'Тестовая страница': test_page.md